### ISSUE TITLE
Add question is not working properly

### ISSUE THREAD

**Issue by lingawarp** [QuodeIT/Quodeitv1.1#44]
when we pressed save and proceed, it doesn't stop loading.

**Comment by tripples** [comment]
which question mcq, subjective ? please mention type in all related types.
It is always better if print url on which you get issue.

**Comment by lingawarp** [comment]
it was for all question irrespective of question type.

**Comment by tripples** [comment]
Assuming it is working now for all. Closing issue. Reopen if you feel any problems.

Please verify on your side once on both browsers.
